openapi: 3.0.0
info:
  version: 1.0.0
  title: Simulation Data API
  description: A simple API to connect with driving simulator in real-time

paths:
  /:
    get:
      summary: Get request that returns simulation data
      responses:
        '200':
          description: Successfully returned data as a json object
          content:
            application/json:
              schema:
                type: object
              examples:
                Velocity and Time:
                  value:
                    {
                      "Velocity": 50,
                      "SimTime": 120
                    }
                YPosition and Velocity:
                  value:
                    {
                      "YPosition": 243.28,
                      "Velocity": 37
                    }


  /update:
    post:
      summary: Post request to update simulation data
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: json file
      responses:
        '200':
          description: Successfully updated the data
        '415':
          description: The content type was not application/json
        '400':
          description: Received json data that was incorrectly formatted

